"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](light_black)\
$os\
$username\
[](fg:light_black bg:blue)\
$git_branch\
$git_status\
[](fg:blue bg:cyan)\
$directory\
[ ](fg:cyan)\
$line_break$character"""

palette = 'neon_heroes'

[palettes.neon_heroes]
black         = "#0a0a0f"
red           = "#ff0055"
green         = "#00ffcc"
yellow        = "#ffff66"
blue          = "#00aaff"
magenta       = "#cc00ff"
cyan          = "#00ffff"
white         = "#dcdcdc"
light_black   = "#2d2d3d"
light_red     = "#ff3399"
light_green   = "#66ffd9"
light_yellow  = "#ffff99"
light_blue    = "#33ccff"
light_magenta = "#ff66ff"
light_cyan    = "#66ffff"
light_white   = "#ffffff"
danger        = "#ff3399"  # for errors/warnings

[os]
disabled = false
style = "bg:light_black fg:light_white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:light_black fg:light_white"
style_root = "bg:light_black fg:light_white"
format = '[ $user ]($style)'

[directory]
style = "fg:light_black bg:cyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol $branch ](fg:light_black bg:blue)]($style)'

[git_status]
style = "bg:cyan"
format = '[[($all_status$ahead_behind )](fg:light_black bg:blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:magenta)'
vimcmd_replace_symbol = '[](bold fg:magenta)'
vimcmd_visual_symbol = '[](bold fg:light_magenta)'
