alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

function docker() {
    if [[ "$*" == "image ls -A" ]]; then
        command docker image ls -a 2>/dev/null | grep -v "vsc"
    elif [[ "$*" == "container ls -A" ]]; then
        command docker container ls -a 2>/dev/null | grep -v "vsc"
    else
        command docker "$@"
    fi
}

